### ISSUE TITLE
Design Review v11

### ISSUE THREAD

**Issue by edspark** [sparkfun/MyoWare_Cable_Shield#6]
1) Does it pass DRC with top/bottom keepout layers on? [NO]
comment: There are some errors that have not been approved, but that aren't an issue. 

2) If there are any DRC errors, have they all been approved? [NO]
comment: No, but I addressed this question on the previous comment.

3) Is the name of the board on the board? [YES]
comment: 
Yes! However, the images for "Advancer Technologies", "Myoware", the flexing Arm, and 
the Advancer symbol are all bitmap images and not vector. This greatly increases the time on 
the CAM job and this would be a great time to convert them. Mike Hord has a script for converting these images or so I'm told. Thanks!

**Comment by elizabethsrobert** [comment]
These issues have been addressed and fixed. Previous DRC errors approved.
